[EarthEngine]
# ID del proyecto de Google Earth Engine
proyecto_id = imagenes-satelitales-490002

[Rutas]
# Carpeta donde se guardaran los CSVs resultantes.
# Puedes usar ~ para referirte a tu carpeta de usuario (ej. C:\Users\TuUsuario)
carpeta_salida = ~/Desktop/imagenes_satelitales/analisis_ndvi_multiple

[Defaults]
# Coordenadas y fechas iniciales por defecto al ejecutar el script
latitud_default = -34.652483699
longitud_default = -61.362346398
fecha_inicio_default = 2025-04-02
fecha_fin_default = 2025-11-11
